Metaswitch/ralf

- debian/ralf.init.d
- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf
- src/main.cpp
Fixes #107.
Tested the init.d changes by:
* checking that Ralf starts up normally
* checking the debug logs to confirm the startup options were recognised
```
15-12-2014 22:44:11.199 UTC Status main.cpp:319: Log level set to 5
15-12-2014 22:44:11.200 UTC Info main.cpp:329: Command-line options were: /usr/share/clearwater/bin/ralf --localhost=10.249.61.134 --http=10.249.61.134 --http-threads=50 --access-log=/var/log/ralf --log-file=/var/log/ralf --log-level=5 --billing-realm=example.com --sas=0.0.0.0,ralf@10.249.61.134 
15-12-2014 22:44:11.200 UTC Info main.cpp:167: Local host: 10.249.61.134
15-12-2014 22:44:11.200 UTC Info main.cpp:177: HTTP address: 10.249.61.134
15-12-2014 22:44:11.200 UTC Info main.cpp:203: HTTP threads: 50
15-12-2014 22:44:11.200 UTC Info main.cpp:218: Access log: …
```
> Protect against bad config

- src/session_manager.cpp
Simple fix for a dangling pointer. Tested by checking the UTs still pass.
> [Reviewer: Andy] Fix dangling pointer if retrieving a session fails

- src/main.cpp
- src/sessionstore.cpp
This PR should only be merged after we have delivered a release where the default format was binary.
> Switch the default session store write format to json

- debian/control
- mk/libmemcached.mk
This:
* fixes up the Boost dependencies, like everywhere else
* makes the libmemcached Makefile change discussed in https://github.com/Metaswitch/libmemcached-upstream/pull/6
I've tested the latter by running `make clean`, checking that `modules/libmemcached/configure` was removed, and that a subsequent `make` rebuilt it and everything that depends on it.
If you're happy with that, I'll make the same change (without review) to the other libmemcached.mk files elsewhere.
> [Reviewer: Ellie] 14.04 dependency fixes

- src/main.cpp
Fixes https://github.com/Metaswitch/sprout/issues/973 (partly)
> [Reviewer: Andy] Ensure process name passed to openlog() lasts for duration of program

- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_remote_memcached_plugin.py
Identical to corresponding Sprout change.
> [No reviewer] Don't load remote memcached plugin if there's no remote site

- include/ralf_pd_definitions.h
- src/main.cpp
Without this fix, Ralf cyclically crashes (and dumps core) when /var/lib/ralf/ralf.conf is missing (as it will be before configuration has synchronized).  This fix means that it logs in an error and exits cleanly.  This means we don't kill the disk with core files.
> [Reviewer: Andy] Don't crash if /var/lib/ralf/ralf.conf missing

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf
We can't currently install Ralf using etcd because ralf_hostname isn't set yet.  I've coded the same fix as you applied to Homestead at https://github.com/Metaswitch/homestead/commit/cb3ce289e536d1fa83f192d9ece1c008315c47e2.
Please can you have a think about whether there are any other repos that need fixing up in this way?  (I haven't hit any yet.)
> [Reviewer: Andy] Don't fail infrastructure scripts

- src/main.cpp
Matt, along with https://github.com/Metaswitch/homestead/pull/231 and https://github.com/Metaswitch/memento/pull/82, I think these are all the blacklist duration defaults that need setting. They're already set correctly in Sprout. Do you agree?
> Reviewer MIRW: Set default blacklist durations

- src/sessionstore.cpp
As discussed. We've seen race conditions under stress where the data gets erased too early.
> Reviewer AMC: Keep data around in memcached for longer

- include/ralf_pd_definitions.h
- src/main.cpp
We didn't seem to previously shut down the Diameter stack in Ralf :( Also, added a PD log (matching the one in Homestead) and corrected another PD log...
> Reviewer RKD: Shutdown Diameter stack

- ralf.root/usr/share/clearwater/bin/poll_ralf.sh
Same as https://github.com/Metaswitch/clearwater-infrastructure/pull/332, but for this repo.
> Switch from Python version of bracket_ipv6_address to C++ version

- debian/ralf.init.d
- src/main.cpp
This change adds support for a config parameter to control whether SAS traffic is routed via the signaling network instead of the (default) management network.  
Tested using tcpdump to confirm that the signaling namespace is used for SAS traffic iff this parameter is set to "Y".
Associated PRs for ralf, homestead and readthedocs will be linked below
> [Reviewer AJH] Optionally route sas traffic via signaling namespace

- src/main.cpp
This stops Ralf crashing when trying to connect to remote memcached stores.
> [Reviwer: EM] Create a (de)serializer before writing to each memory store

- debian/ralf.init.d
- src/main.cpp
rather than just using the configured ralf hostname for chronos callbacks. This
allows us to configure chronos to always call back to ralfs in the local site
Testing done:
- live tested
> [Reviewer: Ellie] Add chronos-ralf-callback-uri option

- debian/ralf.init.d
- src/main.cpp
This is implementing similar function as is in Sprout, to fix https://github.com/Metaswitch/ralf/issues/250 .
Tested live, setting the `signaling_dns_server` option in local_config `1.1.1.1,1.1.2.2`. 
The logs show this being picked up:
```
11-11-2016 14:05:11.641 UTC Status dnscachedresolver.cpp:150: Creating Cached Resolver using servers:
11-11-2016 14:05:11.641 UTC Status dnscachedresolver.cpp:160:     1.1.1.1
11-11-2016 14:05:11.641 UTC Status dnscachedresolver.cpp:160:     1.1.2.2
```
Running `tcpdump net 1.1.0.0/16` showed ralf attempting to contact these two IPs separately for DNS resolution, as below:
```
14:05:55.909428 IP ec2-54-152-83-155.compute-1.amazonaws.com.56405 > 1.1.1.1.domain: 36183+ SRV? _diameter._tcp.cdf.ajl.cw-ngv.com. (51)
14:05:55.909454 IP …
```
> [Reviewer: Ellie] Parse for multiple DNS servers in main

- src/handlers.cpp
Move send_http_reply to after handling the message so the load monitor latency
accurately reflects the time taken to send the reply
Fixes #58 
**Testing**
Live tested with manual change to add extra latency to ensure that the load monitor is getting the true value of the latency
> [Reviewer: Ellie] better load monitor latency stats

- include/rf.h
- src/rf.cpp
- src/ut/test_rf.cpp
Completed bug fix.
Field has been added in.
Field: Service-Context-Id
Value: MNC.MCC.10.32260@3gpp.org
Have tested field is present and looks right by printing it out.
Fix to #262
> Added the Service-Context-Id AVP to ACRs

- debian/ralf.init.d
- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
- src/main.cpp
Ellie,
As discussed the other day, we'd like to be able to configured whether Ralf is enabled based on whether there is a configured host name. If it isn't enabled, we shouldn't start it or allow it to be started, and we shouldn't monitor it, or any of it's children.
To this end, I've made two changes:
- Add/remove the monit script based on whether Ralf is present
- Prevent Ralf from starting if there is no configured Ralf hostname
> [Reviewer: EM] Don't run Ralf if there is no Ralf hostname.

- debian/ralf.init.d
- include/handlers.hpp
- src/main.cpp
In order to reduce the volume of data logged to SAS, we've made the logging of Ralf HTTP bodies optional. By default, the bodies will not be logged (the messages appear in SAS with the generic string <Body present but not logged>).
If required, the parameter http_acr_logging=Y can be set in shared_config to turn this logging back on.
This PR covers the Ralf-side changes. There are some similar changes to Sprout - see [here](https://github.com/Metaswitch/sprout/pull/1845).
> Optionally log Ralf HTTP bodies to SAS

- debian/ralf.init.d
- include/peer_message_sender.hpp
- include/peer_message_sender_factory.hpp
- include/rf.h
- src/handlers.cpp
- src/main.cpp
- src/peer_message_sender.cpp
- src/rf.cpp
- src/session_manager.cpp
- src/ut/coverage-not-yet
- src/ut/test_handlers.cpp
- src/ut/test_session_manager.cpp
This PR:
- Sets a diameter timeout so that we don't leak memory if the CCF is unresponsive. I've copied code from homestead so that we set the same defaults if the diameter timeout config option is not set.
- Adds UTs to get code coverage in most of Ralf.
> [Reviewer: EM] Set diameter timeout and add code coverage

- src/session_manager.cpp
Fixes issue [#2050](https://github.com/Metaswitch/clearwater-issues/issues/2050) so that a SAS event for the creation of an interim timer is only logged if the timer is actually created.
> Fix interim timer SAS logging (issue #2050)

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf
Introduces a shared config option to set the delay between watchdog messages in freeDiameter, defaulting to 30s.
The script has undergone very basic live testing, with more to come.
> [Reviewer: AJH] Add watchdog timer config option

- src/Makefile
- src/main.cpp
- src/ut/test_session_manager.cpp
PR to update Ralf to use the new HttpRequest/HttpClient API. As all of the actual changes are within the cpp-common owned connection classes, the changes here are primarily around the change to construction of these modules. 
I've also taken the chance to update `fake_chronos` to `mock_chronos` in hte UTs, as it is actually a mock chronos connection
> Http rework
