Metaswitch/ralf

- debian/ralf.init.d
- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf
> Protect against bad config (updated)

- include/ralfsasevent.h
- include/sessionstore.h
- src/Makefile
- src/main.cpp
- src/sessionstore.cpp
- src/ut/test_session_manager.cpp
- src/ut/test_sessionstore.cpp
Ellie, please can you review my changes to migrate Ralf to using JSON for it's session store. This should match the design you reviewed. 
I have tested this in UT. I am also doing a manual live test, but this shouldn't prevent you from reviewing. 
You have already reviewed the docs for this (as part of the previous sprout work).
> [Reviewer: Ellie] Memcached schema changes

- src/handlers.cpp
- src/ralf_transaction.cpp
Some formatting fix ups, and initialising a variable that may be used uninitialised.
Run the UTs.
Ralf is now bug free.
> Reviewer RKD: A few minor fixups from code reading

- debian/ralf.init.d
- src/main.cpp
Rob, can you review these changes to make the load monitor configurable. They're basically the same as https://github.com/Metaswitch/sprout/pull/944.
> [Reviewer: Rob] Make load monitor options configurable

- debian/control
- src/Makefile
- src/main.cpp
Andy,
Please can you review this change to integrate Astaire with Ralf?
Thanks,
Matt
> [Reviewer: Andy] Astaire integration

- include/ralfsasevent.h
- include/session_manager.hpp
- src/handlers.cpp
- src/session_manager.cpp
The Ralf equivalent of https://github.com/Metaswitch/sprout/pull/978
> [Reviewer: Andy] New sas events

- ralf.root/usr/share/clearwater/bin/poll_ralf.sh
- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
Ralf changes (following template of https://github.com/Metaswitch/chronos/pull/107)
> [Reviewer: Matt] Monit changes

- debian/control
Same fix as Metaswitch/homestead#194.
> [No review required] Ralf depends on libevent-2.0.5 and libcurl3-gnutls

- debian/ralf.init.d
Same as https://github.com/Metaswitch/homestead/pull/207.
> [Reviewer: Andy] Add service run command to run blocking

- debian/ralf.init.d
- src/main.cpp
Same as https://github.com/Metaswitch/sprout/pull/1023.
> [No review required] Make DNS blacklist duration configurable

- ralf.root/usr/share/clearwater/clearwater-diags-monitor/scripts/ralf_diags
Graeme, please could you review this PR to check Ralf's connectivity to the billing realm. This is the Ralf equivalent of https://github.com/Metaswitch/homestead/pull/215, and was tested in basically the same way.
> [Reviewer: Graeme] Check Ralf's connectivity to the billing realm

- debian/ralf.postinst
- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_chronos_plugin.py
Rob, can you look over the chronos plugin for Ralf. This should be the same as Sprout
> [Reviewer: Rob] Ralf chronos plugin

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_memcached_plugin.py
- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_remote_memcached_plugin.py
No review needed - just a cpp-common update and some plugin changes equivalent to the Sprout ones
> [No reviewer] Allow etcd GR

- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_chronos_plugin.py
- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_memcached_plugin.py
- ralf.root/usr/share/clearwater/clearwater-cluster-manager/plugins/ralf_remote_memcached_plugin.py
Co-req change to accompany Metaswitch/clearwater-etcd#70
> Etcd plugins now receive parameter objects

- src/main.cpp
> [No reviewer] Pull in alarms fix

- ralf.root/usr/share/clearwater/infrastructure/alarms/ralf_alarms.json
Equivalent of https://github.com/Metaswitch/sprout/pull/1172
> No reviewer: Edit Chronos connection alarm

- debian/ralf.postinst
- debian/ralf.prerm
Minor improvements to the Ralf postinst/prerm files. I've got similar changes for Homestead/Memento/Alarms-agent as well (but I won't send these for review)
Fixes #168
> [Reviewer: Rob] Minor fixes for the postinst/prerm files

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf
Similar fix to https://github.com/Metaswitch/crest/pull/229
> [No reviewer] Check config before running scripts

- README.md
- docs/API.md
- docs/Development.md
Hi Rob,
Please can you review the Ralf docs I've added. Do you think any other docs would be useful? Obviously Ralf doesn't do a great deal so it didn't feel like there was much else.
Fixes https://github.com/Metaswitch/ralf/issues/106.
Thanks,
Graeme
> Reviewer RKD: Documentation

- src/session_manager.cpp
- src/sessionstore.cpp
> Reviewer AMC/MIRW: Accounting record numbers

- debian/ralf.init.d
- src/main.cpp
Merging without review, same principle as https://github.com/Metaswitch/chronos/pull/191.
> [No reviewer] Implement a properly locked pidfile

- debian/ralf.init.d
- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
Markup to https://github.com/Metaswitch/ralf/pull/187.
> [No reviewer] Move the pidfile into a writeable directory

- src/Makefile
- src/ut/test_session_manager.cpp
Use new MockChronosConnection added in https://github.com/Metaswitch/cpp-common/pull/411
> [No reviewer] Use new style MockChronosConnection

- debian/ralf.init.d
> [No reviewer] Create the pidfile directory even on 'make run'

- ralf.root/usr/share/clearwater/infrastructure/alarms/ralf_alarms.json
- src/main.cpp
Updates to use new communication monitor for raising alarms and logs.
> [No Reviewer] Astaire alarm log updates

- debian/ralf.postinst
- debian/ralf.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- debian/ralf.init.d
- debian/ralf.prerm
> [No reviewer] Set PID ownership

- debian/ralf.init.d
> [No reviewer] chown_r

- src/main.cpp
Same as https://github.com/Metaswitch/astaire/pull/51
> [No reviewer] Remove call to clear all alarms

- debian/ralf.init.d
Set up defaults, then dot in config files
> [Reviewer: Graeme] Make ralf consistent with Homestead/Sprout

- debian/ralf.init.d
- src/main.cpp
Following the change in https://github.com/Metaswitch/cpp-common/pull/505
> [No reviewer] Use new signal handler start

- src/main.cpp
Uses https://github.com/Metaswitch/cpp-common/pull/511
> [No reviewer] Split signal handlers and utils

- src/main.cpp
Matching change to https://github.com/Metaswitch/sprout/pull/1444
> [No reviewer] Always make an ENT log for bas SAS config

- src/Makefile
- src/main.cpp
Using the new AlarmManager from https://github.com/Metaswitch/cpp-common/pull/526
> Use the new AlarmManager

- debian/ralf.logrotate
- src/main.cpp
This adds standard error / standard output logging to ralf.
> [Reviewer: MIRW] Use common daemon setup/logging

- src/main.cpp
Fix a few bugs from the merge:
- commas.
- access_logger not initialized.
> [Reviewer: GDR] Fix bugs from merging dev into split-clusters.

- Makefile
- debian/.gitignore
- debian/control
> [Reviewer: AJL] Split storage debian packaging for Ralf

- include/ralf_pd_definitions.h
- src/Makefile
- src/main.cpp
Friend of https://github.com/Metaswitch/cpp-common/pull/574
> Reviewed: Use real syslog

- docs/API.md
I noticed an error in this doc, so I fixed it.
> Reviewer AJL: Correct lost BYE behaviour

- debian/ralf.init.d
- src/main.cpp
Companion PR to Metaswitch/cpp-common#641
> [Reviewer EM] Plumb through DNS timeout

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
As per https://github.com/Metaswitch/sprout/pull/1863
> [No reviewer] Don't wait for 6 cycles before killing a process

- ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
As per https://github.com/Metaswitch/homestead/pull/458 we will clamp Ralf to 40% as well.
> [No reviewer] Clamp memory usage to 40%

- src/main.cpp
This removes the code from Ralf that's moved to cpp-common under https://github.com/Metaswitch/cpp-common/pull/662
> [Reviewer: Seb] Move duplicated code to cpp-common

- debian/control
Equivalent to https://github.com/Metaswitch/sprout/pull/2055
> [Reviewer: Richard] Add rogers to ralf-node package

- ralf.root/etc/cron.hourly/ralf-log-cleanup
Can you review this one liner please?
Testing:
Create >2 files - check they're deleted
I'm not going to test the size limit works (since the only way to do that would be to make two files that were 750MB and it doesn't actually test much)
> [Reviewer: RJW]Tidy up ramrecorder logs

- debian/control
`make deb` works.  Feel free to just merge in if you're happy
> [Reviewer=RJW2] Add boost-thread dependency

- debian/ralf.init.d
- ralf.root/etc/cron.hourly/ralf-log-cleanup
- src/main.cpp
Code has already been reviewed.
> [No reviewer] Naive ram recorder

- debian/ralf.init.d
- src/main.cpp
See also Metaswitch/cpp-common#773
> Add support for RAM recording everything
